<template>
  <div class="taphouse-select-container">
    <select id="taphouseSelect" :data-placeholder="placeholder" :multiple="multiple" class="chosen-select" @change="onChange($event)">
      <option v-for="option in venues" :key="option[trackBy]" :value="option[trackBy]">
        {{ option[label] }}
      </option>
    </select>
  </div>
</template>

<script>
export default {
  name: 'VenueSelect',
  data () {
    return {
      label: 'name',
      trackBy: 'slug',
      multiple: false,
      placeholder: 'Select a taproom'
    }
  },
  async fetch ({ store }) {
    await store.dispatch('venues/load')
  },
  computed: {
    venues () {
      return [
        { name: 'Select a taproom', id: undefined },
        ...this.$store.state.venues.records
      ]
    }
  },
  methods: {
    onChange (event) {
      this.$router.push('/' + event.target.value)
    }
  }
}
</script>

<style>
.taphouse-select-container {
  flex:1 1 100%;
}

select#taphouseSelect:focus, select#taphouseSelect:active {
  outline:0;
  background: #ffdf7e;
}

/* Select Box */
.taphouse-select-container {
  position: relative;
  margin-bottom: 1rem;
  z-index:10;
  max-width:520px;
  margin-left:auto;
  margin-right:auto;
}

select#taphouseSelect {
  font-size: 1.25rem;
  font-weight: 400;
  line-height:1.25;
  width:100%;
  padding: .75rem 2rem .75rem 3rem;
  border: 0;
  background-color: #ffd34f;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  outline:0;
  z-index:1;
  border-radius:.5rem;
  color:#31302c;
  height:auto;
  overflow:hidden;
  white-space:nowrap;
}

select#taphouseSelect {
  font-size:1rem;
  line-height:1.25;
}

.modal-venue .modal-body {
  padding-top:0;
}

.venue-logo {
  width:64px;
  height:auto;
  margin:0 auto;
  display:block;
}

.venue-title {
  font-size:1.75rem;
  text-align:center;
  margin-bottom:2rem;
  margin-top:.5rem;
}

.venue-info {
  display:flex;
  flex-wrap: wrap;
}

.venue-address, .venue-contact, .venue-social {
  flex: 1 1 33.333%;
  min-width:240px;
}

.venue-taps {
  flex: 1 1 100%;
}

.venue-address, .venue-website, .venue-email, .venue-phone {
  display:block;
  position:relative;
  padding:.25rem 0 .25rem 1.5rem;
}

.venue-address:before, .venue-website:before, .venue-email:before, .venue-phone:before {
  width:1rem;
  height:1rem;
  display:block;
  position:absolute;
  left:0;
  top:.375rem;
  opacity:0.7;
}

.venue-address:before {
    content: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/placeholder.svg);
}

.venue-website:before {
    content: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/internet.svg);
}

.venue-email:before {
    content: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/mail.svg);
}

.venue-phone:before {
    content: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/telephone.svg);
}

.venue-social {
  display:flex;
  justify-content: space-around;
  flex-wrap:wrap;
  padding:1rem 0;
  margin-top: 1.5rem;
}

.venue-social a {
  padding:.5rem;
  opacity:.6;
  border-radius:4px;
}

.venue-social a:hover {
  background:#e5e5e5;
  opacity:1;
}

.venue-social a span {
  max-width:0;
  overflow:hidden;
  display:inline-block;
  vertical-align: middle;
  margin-left: 0;
  transition: max-width .2s ease .05s, margin .2s ease .05s;
}

.venue-social img {
  width:1.5rem;
  height:1.5rem;
}

.chosen-container-single .chosen-single div, .taphouse-select-container:after {
  position: absolute;
  top: 0;
  right: 0;
  display: block;
  width: 3rem;
  height: 100%;
  background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/down-arrow.svg);
  background-size: 1.25rem 1.25rem;
  background-position: 50% 50%;
  background-repeat:no-repeat;
  transition: transform 0.2s ease-out;
  opacity:0.6;
}

.taphouse-select-container:after {
  content:" ";
}

.chosen-container-single .chosen-single:before, .taphouse-select-container:before {
  content:" ";
  display:block;
  position:absolute;
  width:3rem;
  height:3rem;
  top:0;
  left:0;
  background-image: url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/69546/placeholder.svg);
  background-size: 1.5rem 1.5rem;
  background-position: 50% 50%;
  background-repeat:no-repeat;
  opacity:0.6;
}

/*!
Chosen, a Box Enhancer for jQuery and Prototype
by Patrick Filler for Harvest, http://getharvest.com

Version 1.8.7
Full source at https://github.com/harvesthq/chosen
Copyright (c) 2011-2018 Harvest http://getharvest.com

MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
This file is generated by `grunt build`, do not edit it by hand.
*/

/* @group Base */
.chosen-container {
  position: relative;
  display: inline-block;
  vertical-align: middle;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  color:#31302c;
  width:100% !important;
}

.chosen-container .chosen-drop {
  position: absolute;
  top: 100%;
  z-index: 1010;
  width: 100%;
  background: transparent;
  clip: rect(0, 0, 0, 0);
  -webkit-clip-path: inset(100% 100%);
          clip-path: inset(100% 100%);
}

.chosen-container.chosen-with-drop .chosen-drop {
  clip: auto;
  -webkit-clip-path: none;
          clip-path: none;
}

.chosen-container a {
  cursor: pointer;
}

.chosen-container .search-choice .group-name, .chosen-container .chosen-single .group-name {
  margin-right: 4px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  font-weight: normal;
  color: #999999;
}

.chosen-container .search-choice .group-name:after, .chosen-container .chosen-single .group-name:after {
  content: ":";
  padding-left: 2px;
  vertical-align: top;
}

/* @end */
/* @group Single Chosen */
.chosen-container-single .chosen-single {
  position:relative;
  font-size: 1.25rem;
  font-weight: 400;
  line-height:1.25;
  width:100%;
  padding: .75rem 2rem .75rem 3rem;
  border: 0;
  background-color: #ffd34f;
  outline:0;
  z-index:100;
  border-radius:0.5rem;
  color:#31302c;
  overflow:hidden;
  white-space:nowrap;
  display: block;
  transition: box-shadow 0.3s cubic-bezier(.25,.8,.25,1);
}

.chosen-container-single .chosen-single:hover, .chosen-container-single .chosen-single:active, .chosen-container-single .chosen-single:focus {
  background-color:#ffdf7e;
}

.chosen-container-single .chosen-default {
  color: #999;
}

.chosen-container-single .chosen-single span {
  display: block;
  overflow: hidden;
  margin-right: 26px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.chosen-container-single .chosen-single-with-deselect span {
  margin-right: 38px;
}

.chosen-container-single .chosen-single abbr {
  position: absolute;
  top: 6px;
  right: 26px;
  display: block;
  width: 12px;
  height: 12px;
  background: url("/static/img/chosen-sprite.png") -42px 1px no-repeat;
  font-size: 1px;
}

.chosen-container-single .chosen-single abbr:hover {
  background-position: -42px -10px;
}

.chosen-container-single.chosen-disabled .chosen-single abbr:hover {
  background-position: -42px -10px;
}

.chosen-container-single .chosen-search {
  position: relative;
  z-index: 1010;
  margin: 0;
  padding: 0.125rem 3rem 0.125rem 3rem;
  white-space: nowrap;
}

.chosen-container-single .chosen-search input[type="text"] {
  margin: 1px 0;
  padding: .5rem;
  width: 100%;
  height: auto;
  outline: 0;
  border: 1px solid rgba(255,255,255,0.6);
  background: #ffdf7e;
  font-size: 1.25em;
  font-family: sans-serif;
  line-height: normal;
  border-radius: 0;
}

.chosen-container-single .chosen-drop {
  margin-top: -3rem;
  border-radius: .5rem;
  background-clip: padding-box;
}

.chosen-container-single.chosen-container-single-nosearch .chosen-search {
  position: absolute;
  clip: rect(0, 0, 0, 0);
  -webkit-clip-path: inset(100% 100%);
          clip-path: inset(100% 100%);
}

/* @end */
/* @group Results */
.chosen-container .chosen-results {
  color: inherit;
  position: relative;
  overflow-x: hidden;
  overflow-y: auto;
  margin: 0;
  padding: 0;
  max-height: 240px;
  background:#ffd34f;
  -webkit-overflow-scrolling: touch;
}

.chosen-container .chosen-results li {
  display: none;
  font-size:1rem;
  margin: 0;
  padding: .5rem 1rem .5rem 3rem;
  list-style: none;
  word-wrap: break-word;
  -webkit-touch-callout: none;
}

.chosen-container .chosen-results li.active-result {
  display: list-item;
  cursor: pointer;
}

.chosen-container .chosen-results li.disabled-result {
  display: list-item;
  color: #ccc;
  cursor: default;
}

.chosen-container .chosen-results li.highlighted {
  background-color: #ffe594;
}

.chosen-container .chosen-results li.no-results {
  color: #777;
  display: list-item;
  background: #f4f4f4;
}

.chosen-container .chosen-results li.group-result {
  display: list-item;
  font-weight: bold;
  cursor: default;
}

.chosen-container .chosen-results li.group-option {
  padding-left: 15px;
}

.chosen-container .chosen-results li em {
  font-style: normal;
  text-decoration: underline;
}

/* @end */
/* @group Active  */
.chosen-container-active.chosen-with-drop .chosen-single {
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.chosen-container-active.chosen-with-drop .chosen-single div, .taphouse-select-container:focus-within:after {
  transform: rotate(180deg);
}

.chosen-container-active .chosen-choices li.search-field input[type="text"] {
  color: #222 !important;
}

/* @end */

@media (min-width: 375px) {
  select#taphouseSelect {
    font-size:1.25rem;
  }
}

@media (min-width: 420px) {
  html {
    font-size:16px;
  }
  .container-fluid {
    padding-left:1rem;
    padding-right:1rem;
  }
}

@media (min-width: 576px) {
  .container-fluid {
    padding-left: 2rem;
    padding-right: 2rem;
  }
  .modal-dialog {
    max-width: 530px;
  }
  .venue-social a:hover span {
    max-width:100px;
    margin-left: .5rem;
  }
}

@media (min-width:880px) {
  .navbar-logo {
    padding-top:1.25rem;
  }

  .text-intro {
    padding-bottom:1.25rem;
  }

  .taphouse-select-container {
    flex:0 0 50%;
    padding-left:.5rem;
  }

  .taphouse-select-container:before {
    background-position: 90% 50%;
  }
}
</style>
